<a href="https://colab.research.google.com/github/MELRIAN1910/MachineLearning/blob/main/Python_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python basics**

## Print Function

In [ ]:
#Text
print("The Text You Want To Print")
print('hello'*5)

The Text You Want To Print
hellohellohellohellohello


In [ ]:
#slicing
text_1 = "programming"
print(text_1[0:4])
print(text_1[1:5])

prog
rogr


In [ ]:
#step
print(text_1[0:10:2])
print(text_1[0:10:3])

pormi
pgmn


In [ ]:
#Concatenation
text_2 = "is fun"
print(text_1 + text_2)

programmingis fun


In [ ]:
#Number
print(123)

123


## Constants & variables

In [ ]:
DC = "Bat-man"
print(DC)

Bat-man


In [ ]:
marvel1, marvel2, marvel3 = "Iron-man", "Captain-America", "Thor"
print(marvel1)
print(marvel2)
print(marvel3)

Iron-man
Captain-America
Thor


In [ ]:
x = y = z = 23

print(x)
print(y)
print(z)

23
23
23


## Input Function

In [ ]:
number1 = input("Enter a number: ")
number2 = input("Enter a number: ")

sum = number1 + number2
print(sum)

Enter a number: 23
Enter a number: 24
2324


In [ ]:
number1 = input("Enter a number: ")
number2 = input("Enter a number: ")

number1 = int(number1)
number2 = int(number2)

sum = number1 + number2
print(sum)

Enter a number: 23
Enter a number: 24
47


## Data type

In [ ]:
a=8
b= 8.1
c= "hello world"
d = 1+3j
e = True

print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
type(a)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'complex'>
<class 'bool'>


int

## Changing data type

In [ ]:
num = 5
print(num)
print(type(num))

num = float(num)
print(num)
print(type(num))

5
<class 'int'>
5.0
<class 'float'>


## Lists

In [ ]:
my_list = [1,2,3.4,"english",True]
print(my_list)
type(my_list)


[1, 2, 3.4, 'english', True]


list

In [ ]:
#retrieve positional elements by id
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])
print(my_list[4])

1
2
3.4
english
True


In [ ]:
#list can have multiple type of elements
print(type(my_list[0]))
print(type(my_list[1]))
print(type(my_list[2]))
print(type(my_list[3]))
print(type(my_list[4]))

<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [ ]:
#adding elements
my_list.append("new")
print(my_list)

[1, 2, 3.4, 'english', True, 'new']


In [ ]:
#number of elements
print(len(my_list))

6


In [ ]:
#removing elements
my_list.remove("new")
print(my_list)

[1, 2, 3.4, 'english', True]


In [ ]:
#removing elements by index
del my_list[1]
print(my_list)

[1, 3.4, 'english', True]


In [ ]:
#join 2 lists
my_list2 = [1,2,3]
my_list3 = my_list + my_list2
print(my_list3)

[1, 3.4, 'english', True, 1, 2, 3]


## Tuple


In [ ]:
tuple1 = (1,2,3.4,"english",True)
print(tuple1)
type(tuple1)

(1, 2, 3.4, 'english', True)


tuple

In [ ]:
#retrieve positional elements by id
print(tuple1[0])
print(tuple1[1])
print(tuple1[2])
print(tuple1[3])
print(tuple1[4])

1
2
3.4
english
True


In [ ]:
#number of elements
print(len(tuple1))

5


In [ ]:
#converting list into tuple
my_list = [1,2,3]
print(my_list)
my_tuple = tuple(my_list)
print(my_tuple)
type(my_tuple)

[1, 2, 3]
(1, 2, 3)


tuple

## Sets

In [ ]:
mySet = {1,2,3,4,5}
print(mySet)
type(mySet)

{1, 2, 3, 4, 5}


set

In [ ]:
#convert list to set
list1 = [1,2,3,4,5]
print(list1)
x = set(list1)
print(x)
type(x)

[1, 2, 3, 4, 5]
{1, 2, 3, 4, 5}


set

In [ ]:
#doesn't allow duplicate values
set1 = {1,2,3,4,5,5}
print(set1)

{1, 2, 3, 4, 5}


## Dictionary

In [ ]:
myDictionary = {
    "name" : "John",
    "age" : 36,
    "country" : "Norway"
}
print(myDictionary)
type(myDictionary)

{'name': 'John', 'age': 36, 'country': 'Norway'}


dict

In [ ]:
#retrieve a specific data
print(myDictionary["name"])
print(myDictionary["age"])
print(myDictionary["country"])

John
36
Norway


## Operators

### Arithmetic Operators

In [ ]:
num1 = 20
num2 = 6
#Addition
print(num1 + num2)
#subtraction
print(num1 - num2)
#multiplication
print(num1 * num2)
#division float
print(num1 / num2)
#modulus
print(num1 % num2)
#exponent
print(num1 ** num2)
#Division Integer
print(num1 // num2)

26
14
120
3.3333333333333335
2
64000000
3


### Assignment Operator

In [ ]:
a=5
b = 5
c = 5
d = 5
e = 5
f = 5

In [ ]:
#each time you run the number gets added
a += 5
print("a =", a)

b -= 2
print("b =", b)

c *= 2
print("c =",c)

d /= 2
print("d =",d)

e **= 2
print("e =",d)

f %= 2
print("f =",f)

a = 35
b = -7
c = 320
d = 0.078125
e = 0.078125
f = 1


### Comparison Operator

In [ ]:
a = 10
b = 20
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

False
True
False
True
False
True


### Logical Operators

In [ ]:
a = 10
print(a > 20 and a > 5)
print(a > 20 or a > 5)
print(not(a > 20 and a > 5))

False
True
True


### Idendity Operators

In [ ]:
x = 5
y = 5
z = 10
print(x is y)
print(x is not y)
print(x is z)
print(x is not z)

True
False
False
True


### Membership Operators

In [ ]:
a = 5
b = 10
c = [1,2,3,4,5]
print(a in c)
print(b in c)
print(a not in c)
print(b not in c)

True
False
False
True


## Conditional statements

In [ ]:
#simple if else
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))

if a > b:
  print("first number is greater")
else:
  print("2nd number is greater")

Enter a number: 10
Enter a number: 20
2nd number is greater


In [ ]:
#if elif else

a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
c = int(input("Enter a number: "))

if b < a > c:
  print("first number is greater")
elif a < b > c:
  print("2nd number is greater")
else:
  print("3rd number is greater")

Enter a number: 10
Enter a number: 20
Enter a number: 30
3rd number is greater


In [ ]:
#nested if
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
c = int(input("Enter a number: "))

if a > b:
  if a > c:
    print("first number is greater")
  else:
    print("3rd number is greater")

else:
  if b > c:
    print("2nd number is greater")
  else:
    print("3rd number is greater")

Enter a number: 10
Enter a number: 30
Enter a number: 20
2nd number is greater


## For Loops

In [ ]:
a = 5
for i in range(a):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9


In [ ]:
for i in range(3):
  laptop_price =int(input("Enter the price of laptop: "))
  print(laptop_price)

Enter the price of laptop: 600000
600000
Enter the price of laptop: 2700000
2700000
Enter the price of laptop: 5000000
5000000


In [ ]:
numbers = [50,100, 150, 200]
for i in numbers:
  i = i + 5
  print(i)

55
105
155
205


## While Loops

In [ ]:
i = 0
while i < 10:
  print(i)
  i += 1

0
1
2
3
4
5
6
7
8
9


## Functions

In [ ]:
#Example (Factorial)
def factorial_value(num):
  factorial = 1
  if num == 0:
    return factorial
  else:
    for i in range(1, num + 1):
      factorial = factorial * i
    return factorial

print(factorial_value(5))
print(factorial_value(10))
print(factorial_value(6))

120
3628800
720


# Python Libraries

In [ ]:
#Numpy
import numpy as np
#Pandas
import pandas as pd
#Matplotlib
import matplotlib.pyplot as plt
#Seaborn
import seaborn as sns

## NumPy

In [ ]:
#NumPy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# 1 dim array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
print(c)
c.shape

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


(3, 3)

In [ ]:
#Numpy Array of 0s
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#numpy array of a particular value
y = np.full((2,3),5)
print(y)

[[5 5 5]
 [5 5 5]]


In [ ]:
#identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#numpy array with random values
b = np.random.random((2,3))
print(b)

[[0.45291576 0.59034791 0.37015523]
 [0.7454734  0.39326916 0.01874916]]


In [ ]:
#numpy array with random integer values
c = np.random.randint(100, size = (5))
print(c)

[50 24 83 61 93]


In [ ]:
#numpy array with random integer values within specified range
d = np.random.randint(50,100, (3,5))
print(d)

[[80 97 73 62 70]
 [70 99 82 66 98]
 [96 71 94 73 89]]


In [ ]:
#array of evenly spaced values
  #Specify the number of values required
e = np.linspace(10,20,5)
print(e)

  #specify the steps
f = np.arange(10,20,2)
print(f)

[10.  12.5 15.  17.5 20. ]
[10 12 14 16 18]


In [ ]:
#convert list to numpy array
list1 = [10,20,30,40,50]
np_array = np.array(list1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [ ]:
#analyzing a numpy array
c = np.random.randint(10,100, (3,5))
print(c)
#Number of Dimenshions
print("Number of Dimenshions = ", c.ndim)
#Number of Rows and Columns
print("Number of Rows and Columns = ", c.shape)
#Number of elements in an array
print("Number of elements in array = ", c.size)
#checking data types of values in array
print("Data types of values in array = ", c.dtype)

[[79 86 92 16 32]
 [87 24 46 40 25]
 [14 47 58 81 56]]
Number of Dimenshions =  2
Number of Rows and Columns =  (3, 5)
Number of elements in array =  15
Data types of values in array =  int64


In [ ]:
#mathematical operations on np array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print("_____________________________________________________________________________________________________")
#addition
print("Addition")
print(a + b)
print(np.add(a,b))
print("_____________________________________________________________________________________________________")
#subtraction
print("Subtraction")
print(a-b)
print(np.subtract(a,b))
print("_____________________________________________________________________________________________________")
#multiplication
print("Multiplication")
print(a*b)
print(np.multiply(a,b))
print("_____________________________________________________________________________________________________")
#division
print("Division")
print(a/b)
print(np.divide(a,b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
_____________________________________________________________________________________________________
Addition
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
_____________________________________________________________________________________________________
Subtraction
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
_____________________________________________________________________________________________________
Multiplication
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
_____________________________________________________________________________________________________
Division
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#array manipulation
  #transpose
a = np.random.randint(0,10,(3,5))
print(a)
print(                                         )
trans = np.transpose(a)
print("transpose of a is")
print(trans)
print(                                         )
print(trans.shape)

[[2 7 2 6 3]
 [8 5 4 3 9]
 [1 4 7 4 3]]

transpose of a is
[[2 8 1]
 [7 5 4]
 [2 4 7]
 [6 3 4]
 [3 9 3]]

(5, 3)


In [ ]:
#another way to transpose
trans = a.T
print(trans)
print(                                         )
print(trans.shape)

[[2 8 1]
 [7 5 4]
 [2 4 7]
 [6 3 4]
 [3 9 3]]

(5, 3)


In [ ]:
#reshaping array
print(a)
print(a.shape)
b = a.reshape(5,3)
print(b)
print(b.shape)

[[2 7 2 6 3]
 [8 5 4 3 9]
 [1 4 7 4 3]]
(3, 5)
[[2 7 2]
 [6 3 8]
 [5 4 3]
 [9 1 4]
 [7 4 3]]
(5, 3)
